### PR TITLE
Fixed compile error on latest GCC (14.2.1)

### PR DESCRIPTION
**Pull request by NickyBoy89**
This PR contains a fix for a compile error that I noticed while compiling Cobra on my Linux machine:

```bash
cc -I. -Wall -O2 -pedantic -Werror -Wshadow -std=c99 -DYY_NO_INPUT -Wformat-truncation=1   -c -o cobra_prim.o cobra_prim.c
cobra_prim.c: In function ‘dogrep’:
cobra_prim.c:158:75: error: ‘%s’ directive output may be truncated writing up to 2030 bytes into a region of size between 0 and 2030 [-Werror=format-truncation=]
  158 |                         snprintf(cmd, sizeof(cmd), "grep -q -n -e  \"%s\" %s",
      |                                                                           ^~
cobra_prim.c:158:25: note: ‘snprintf’ output between 19 and 4079 bytes into a destination of size 2048
  158 |                         snprintf(cmd, sizeof(cmd), "grep -q -n -e  \"%s\" %s",
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  159 |                                 s, f->s);
      |                                 ~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: cobra_prim.o] Error 1
```

It appears that in the `dogrep` function, the compiler cannot adequately reason about the bounds check that we make to make sure that the resulting command that will be run through grep will not overflow the buffer that was created for it.

This PR separates those steps out into separate variables, and includes a minor refactor to re-copy the grep command into the buffer, instead of modifying the 5th and 6th indexes of the string to remove a flag before it is run again. This I thought made the intent of the code more readable, at the cost of an additional `snprintf`.

### System Details

* OS: Arch Linux, Kernel 6.11.6-arch1-1
* `gcc --version`
  > gcc (GCC) 14.2.1 20240910

### CODE REVIEW

**Comment by NickyBoy89** [comment]
Hmm, it's interesting that the problem seems intermittent, and seems to be very version-dependent. I remember solving a similar type of issue in #65, just in a different place, so something as simple as separating out the variable name fixes it.

I'm using GCC `gcc (GCC) 14.2.1 20240910` (also in the original PR text)

Perhaps it would be worth looking at multiple callsites for `snprintf` at once next time?

**Comment by nimble-code** [comment]
I'm using Ubuntu 22.04.2  LTS  and gcc version 11.4.0 and do not see any warnings.
I'm thinking of just adding a (redundant) length-test on that one argument to snprintf though, to minimize the change, but I wish that I could see the warning go away....

**Comment by nimble-code** [comment]
3 isn't too attractive because it might eliminate also accurate warnings.
2 may not work, because it's complaining about arguments being truncated -- the size written cannot exceed the limit of sizeof(buffer) since snprintf already bounds it (unlike sprintf).
so that leaves 1, which comes down to guessing what the gcc analyzer can understand -- will it be able to figure out that the checks on the length of a and b suffice to prevent the truncation?
but yes, with warnings mapped to errors it has to be fixed somehow, even though with changes in gcc versions it may not hold in all cases...   difficult case -- perhaps only quiet that gcc warning on those platforms that erroneously issue the warning and hope it resolves itself in due time....

**Comment by NickyBoy89** [comment]
I just want to point out that 2 might be a a better option than it appears, because GCC says that it will display the warning when:
1. A combination of heuristics cannot check the size of the format string, and
2. The **return value is not used**

Since 2 does use the return value, this would actually remove this category of errors. But completely up to you!

**Comment by nimble-code** [comment]
ah -- thanks for pointing that out.
47 calls to snprintf in the code -- none of them check the return value....
would  n = snprintf(...); assert(n>0);  suppress the warning?
silly, but perhaps it appeases the gcc checker

**Comment by NickyBoy89** [comment]
From what I've read, I think that would work to catch formatting errors (negative return value), but I think I will draft up another PR to add the checks to this, if solution (2) sounds like the best one

**Comment by NickyBoy89** [comment]
Continued and rewritten in #76

**Comment by Beeram12** [comment]
@nimble-code Hey I am facing similar issue how can I resolve it.I cloned the repo and followed the instruction of building but then suddently I faced this error
image

**Comment by Beeram12** [comment]
@nimble-code 
UPDATE : I modified the line 4275 present in `cobra_prog.y`

from 
`rv->val = fprintf((FILE *) vn->pm, q->lft->s);`
to 
`rv->val = fprintf((FILE *) vn->pm, "%s", q->lft->s);`
then it's working fine

**Comment by nimble-code** [comment]
once the update to version 5.0 is complete this issue will also disappear

**Comment by Beeram12** [comment]
> once the update to version 5.0 is complete this issue will also disappear

Hii may I know when can we expect the next version any aprox time.I am trying to implement COBRA in one of my project so a bit of enthusiasm.

**Comment by nimble-code** [comment]
it's there now

**Pull request closed without merging**
